In [1]:
# !pip install dtale

In [2]:
import pandas as pd
import dtale

In [3]:
data = pd.read_csv("misdata2.csv")

In [4]:
data

    Unnamed: 0                nombre inicial             mayuscula
0            0          Mr. Joe Hull       M          MR. JOE HULL
1            1           Mary Walker       M           MARY WALKER
2            2      Jennifer Vasquez       J      JENNIFER VASQUEZ
3            3      Nathaniel Thomas       N      NATHANIEL THOMAS
4            4          Joseph Davis       J          JOSEPH DAVIS
5            5      Richard Mckenzie       R      RICHARD MCKENZIE
6            6        Brittany Olsen       B        BRITTANY OLSEN
7            7        Natasha Walker       N        NATASHA WALKER
8            8      Mr. Cody Wheeler       M      MR. CODY WHEELER
9            9        Timothy Garcia       T        TIMOTHY GARCIA
10          10           Eric Torres       E           ERIC TORRES
11          11          Jenna Phelps       J          JENNA PHELPS
12          12       George Campbell       G       GEORGE CAMPBELL
13          13          Karen Rivera       K          KAREN RIVERA
14          14         Michael Young       M         MICHAEL YOUNG
15          15          Debbie Lopez       D          DEBBIE LOPEZ
16          16         Tammy Fuentes       T         TAMMY FUENTES
17          17          Michael Neal       M          MICHAEL NEAL
18          18            Mark Bowen       M            MARK BOWEN
19          19       Natalie Watkins       N       NATALIE WATKINS
20          20            Sarah Lane       S            SARAH LANE
21          21         Andrew Chavez       A         ANDREW CHAVEZ
22          22          Shelby Bates       S          SHELBY BATES
23          23          Andrew Lopez       A          ANDREW LOPEZ
24          24        Mark Rodriguez       M        MARK RODRIGUEZ
25          25          Mary Simpson       M          MARY SIMPSON
26          26         Latoya Porter       L         LATOYA PORTER
27          27      April Stephenson       A      APRIL STEPHENSON
28          28            Alex Burke       A            ALEX BURKE
29          29         Kevin Simmons       K         KEVIN SIMMONS
30          30          Megan Cooper       M          MEGAN COOPER
31          31        Crystal Hurley       C        CRYSTAL HURLEY
32          32           Tammy Wells       T           TAMMY WELLS
33          33       Christina Adams       C       CHRISTINA ADAMS
34          34         Anthony Payne       A         ANTHONY PAYNE
35          35           Susan Huang       S           SUSAN HUANG
36          36   Christopher Stanton       C   CHRISTOPHER STANTON
37          37           Phillip Lam       P           PHILLIP LAM
38          38  Dr. Jacqueline Duran       D  DR. JACQUELINE DURAN
39          39          Justin Smith       J          JUSTIN SMITH
40          40        Rebecca Hester       R        REBECCA HESTER
41          41       Collin Thompson       C       COLLIN THOMPSON
42          42          Katrina Reed       K          KATRINA REED
43          43          Charles Rios       C          CHARLES RIOS
44          44       James Patterson       J       JAMES PATTERSON
45          45         Raymond Costa       R         RAYMOND COSTA
46          46          Susan Miller       S          SUSAN MILLER
47          47             Lisa Hale       L             LISA HALE
48          48         Robin Goodman       R         ROBIN GOODMAN
49          49       Stephanie Craig       S       STEPHANIE CRAIG
50          50       Catherine Moran       C       CATHERINE MORAN

In [5]:
# Abre una pestaña con la UI de D-Tale
d = dtale.show(data)
d.open_browser()  # opcional: fuerza la apertura automática